#!/bin/bash
if [ ! $1 ]
	then
		echo "No argument supplied for build update:"
		echo " * Argument should contain folder path and dme name."
		exit 1
fi

DME_PATH=$1
DME_NAME=$1

if [ $2 ]
	then
		DME_NAME=$2
fi

cd ./$DME_PATH
git pull --ff-only
DreamMaker -clean $DME_NAME.dme
exit 0
